jv - update footer to include systemInfo.soureRepo value
ucsb-cs156-f22/f22-6pm-happycows pull request #18
Opened 2022-11-22 00:01 UTC by heyyysus

In this PR, 
- we update the footer to use the value from "/api/systemInfo". Will use "#" if that value is undefined. 
- Created stories for the footer and updated systemInfoFixtures to include systemInfo.sourceUrl value. 
- Updated tests for footer to check for sourceUrl value.

2022-11-25 23:00 UTC, pconrad requested changes
One very small change requested, otherwise LGTM.

If you make that small change and get a peer code review, this is likely ready to merge.

2022-11-26 01:52 UTC, heyyysus commented on frontend/src/main/components/Nav/Footer.js
>          </p>
Backup value has changed.

2022-11-26 18:53 UTC, pconrad approved these changes
LGTM

2022-11-27 05:30 UTC, jcucsb approved these changes
Deployed on Heroku. Change for the footer is correct per the issue and necessary files have been added and updated. Passes CI/CD checks and works as expected LGTM!

2022-11-29 00:35 UTC, merged