Frontend changes to allow admin to launch Update Cow Health and Instr…
ucsb-cs156-f22/f22-6pm-happycows pull request #31
Opened 2022-11-25 01:00 UTC by BenYangSB

Frontend changes to allow admin to launch Update Cow Health and Instructor report. Currently only have placeholders for the forms that launch a test job. 

# Demo

![image](https://user-images.githubusercontent.com/1119017/204635332-8d4fdf40-6490-4067-b693-f4859944d20e.png)

2022-11-25 22:44 UTC, pconrad requested changes
Here's how you can look up what changes are needed to pass pitest:

![image](https://user-images.githubusercontent.com/1119017/204061113-1763a905-7f7f-4e19-9413-08ed60c6de44.png)

2022-11-25 22:44 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJob.java
> +package edu.ucsb.cs156.happiercows.jobs;
Need to write a test for this.   

This file has a good example of how to do that.

https://github.com/ucsb-cs156-f22/f22-6pm-happycows/blob/main/src/test/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJobTests.java

2022-11-25 22:44 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
> +package edu.ucsb.cs156.happiercows.jobs;
Same comment as above.  Needs a test similar to:

https://github.com/ucsb-cs156-f22/f22-6pm-happycows/blob/main/src/test/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJobTests.java

2022-11-25 22:49 UTC, pconrad commented
Also: 

Also, see: https://github.com/ucsb-cs156-f22/f22-6pm-happycows/pull/16/files

Where Vyom may have already done what's needed.   Rebasing on his branch might fix your issues with the tests not passing.

```
git pull --rebase origin vyom-issue14
```

Then fix merge conflicts if any, finally:

```
git push origin BenYang-issue26 -f
```

2022-11-26 18:51 UTC, pconrad commented
Looks like the pitest issues are straightforward to resolve:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1119017/204104573-3fadef4c-8e90-466c-924e-5abf76d77733.png">

You just need tests for the two new jobs; and they can be similar to the existing tests for the MilkTheCowsJob.

2022-11-26 18:52 UTC, pconrad commented
Also: be sure to resolve these two merge conflicts.  I suggest taking the builder, since you can use it in the tests.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/1119017/204104603-c662d471-ba90-4560-a521-ee16696d2884.png">

2022-11-28 06:49 UTC, pconrad requested changes
There's a lot of stuff that needs to be fixed here.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/components/Jobs/InstructorReportJobForm.js
> +    sleepMs: 1000
These parameters serve no purpose for the InstructorReportForm.  

Please remove these.   The same will be true of all of the other jobs except for the TestJob.  That is the only one of the four jobs that has any parameters.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/components/Jobs/InstructorReportJobForm.js
> +      </Form.Group>
Unnecessary--please remove.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/components/Jobs/InstructorReportJobForm.js
> +      </Form.Group>
Unnecessary--please remove.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/components/Jobs/InstructorReportJobForm.js
> +    </Form>
The submit button is the only thing needed in the form.   True of the other two jobs that aren't the test job.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/components/Jobs/UpdateCowHealthJobForm.js
> +    sleepMs: 1000
unnecessary; please remove

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/components/Jobs/UpdateCowHealthJobForm.js
> +      </Form.Group>
unnecessary; please remove

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/components/Jobs/UpdateCowHealthJobForm.js
> +      </Form.Group>
unnecessary; please remove

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
> -
Please do not remove this, and refactor in this way.  The change you have made doesn't make the code better; only longer and harder to maintain.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
> -            form: <JobComingSoon />
Just replace this line with 
```suggestion
form: <UpdateCowHealthJobForm submitAction={submitCowUpdateHealthJob} />
```

NOT testJob!

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
> +                       <InstructorReportJobForm submitAction={submitTestJob} />
why are you submitting the test job when the instructor wants an Instructor Report?

submitTestJob submits a test job.   You need a submitAction that submits an Instructor Report job.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
>                  </Accordion.Item>
The preferred refactor would be to get rid of lines 67 through 73 of the original code and instead put another item in the jobLaunchers array that looks like this:

```
{
   name: "Test Job"
   form: <TestJobForm submitAction={submitTestJob} />
}

```

You are refactoring in the wrong direction, take short dry code,  and making it long and repetitive.
Please don't do that.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
> +                       <UpdateCowHealthJobForm submitAction={submitTestJob} />
You need a submit action for an Update Cow Health Job.

You cannot use submitTestJob here, since it submits the wrong job!

2022-11-28 06:49 UTC, pconrad commented on frontend/src/tests/components/Jobs/InstructorReportJobForm.test.js
> +    expect(await screen.findByTestId("InstructorReportJobForm-sleepMs")).toBeInTheDocument();
We absolutely do NOT expect these to be in the document.

Please remove.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/tests/components/Jobs/InstructorReportJobForm.test.js
> +  });
No.... we don't need or want any of this.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/tests/components/Jobs/UpdateCowHealthJobForm.test.js
> +    expect(await screen.findByTestId("UpdateCowHealthJobForm-sleepMs")).toBeInTheDocument();
Nope

2022-11-28 06:49 UTC, pconrad commented on frontend/src/tests/components/Jobs/UpdateCowHealthJobForm.test.js
> +  });
None of this.

2022-11-28 06:49 UTC, pconrad commented on frontend/src/tests/pages/AdminJobsPage.test.js
> +//        expect(await screen.findByText("Milk The Cows")).toBeInTheDocument();
Why are you removing this?  We still need this job!

In fact, it would helpful if you implemented this one too, at the same time.

2022-11-28 06:49 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
> +    @ApiOperation(value = "Launch Instructor Report Job (click fail if you want to test exception handling)")
Remove the "click fail" stuff.  There's no fail parameter here.

2022-11-28 06:49 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
> +    @ApiOperation(value = "Launch Update Cow Health Job (click fail if you want to test exception handling)")
Remove the (click fail) stuff.   There's no fail to click here.

2022-11-28 20:44 UTC, irenecho75 submitted a review, later dismissed
LGTM, but double check when instructors review that it's ok to delete JobComingSoon.js

2022-11-29 00:40 UTC, pconrad approved these changes
LGTM! Will test on qa

2022-11-29 00:48 UTC, pconrad requested changes
So close!  Works perfectly except for launching the milk the cows job, which returns an error.

This is why... there is a mismatch between the url requested by the frontend and the actual url for the backend.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1119017/204410976-f2eb909e-9279-4ad0-ae44-27cb5a6c7bfe.png">

Which results in everything working perfectly except launching the milk the cows job:

![image](https://user-images.githubusercontent.com/1119017/204411017-816fdcd3-a128-46c4-901a-f846e6d85658.png)

2022-11-29 19:59 UTC, pconrad reviewed
LGTM!

2022-11-29 19:59 UTC, merged