ad - Add column called username to leaderboard that maps user id to the correct username
ucsb-cs156-f22/f22-6pm-happycows pull request #69
Opened 2022-12-01 01:07 UTC by akdas16

Added a column called 'Username' in the Leaderboard table, and modified its corresponding test to ensure all column headers and content are displayed correctly.

Closes #25

2022-12-01 01:43 UTC, singhvyom approved these changes
LGTM

2022-12-01 02:06 UTC, xxzjh requested changes
I think you should also edit the fixture file for storybook

2022-12-01 02:46 UTC, akdas16 commented
Do I have to make changes to Leaderboard fixtures (suggested by Jinghan)? I don't think it is necessary.

2022-12-01 03:12 UTC, pconrad requested changes
This is not the correct way to do this.

This adds a redundant field to the database, when the username is already associated with the userid.

Instead, we should create a "DTO" (data transfer object) that combines the information from the UserCommons and the User and sends it through a new endpoint, similar to how the CommonsPlus object works.

2022-12-06 03:17 UTC, pconrad requested changes
This is not the approach we want to take.  I suggest that we just close this PR without merging.

2022-12-06 03:17 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
> +  private String username;
So we did add username to the usercommons in one of the other code bases, but this was a mistake.  We should not have done this, and we are going to have to undo it.

username is already available through the userid, and we should always get it through the user id.  It is bad design to store redundant data in the database.   So this cannot be merged in this form.

2022-12-06 03:17 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
> +  private String username;
This link shows how this should be implemented: as additional functionality in the UserCommonsController:

https://github.com/ucsb-cs156-f22/f22-7pm-happycows/blob/main/src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java#L145

2022-12-06 03:18 UTC, pconrad commented
Closing this without merging.   This is not the approach that we should take to adding username.

The 7pm codebase did this correctly, so we'll use that approach for the S23 codebase.

2022-12-06 03:18 UTC, closed without merging