jz - added a placeholder for the JobMilktheCows
ucsb-cs156-f22/f22-6pm-happycows pull request #8
Opened 2022-11-17 03:01 UTC by xxzjh

<img width="778" alt="Screen Shot 2022-11-16 at 7 00 18 PM" src="https://user-images.githubusercontent.com/88663564/202344201-bb5ee8f2-30ad-4d10-a411-79b8a9ecb3be.png">

replace the origin placeholder <JobComingSoon /> into the new placeholder to launch the "Milk the Cows" job

2022-11-17 03:41 UTC, pconrad requested changes
Could we rename "JobMilktheCows.js to MilkCowsJobForm.js so that it is consistent with TestJobForm.js?

Also, could we go ahead and put this in the component?  That way the component is ready to go when we are ready to hook it up to the backend.

```jsx
 
 <Form onSubmit={handleSubmit(submitAction)}>
      <Button type="submit" data-testid="MilkCowsForm-Submit-Button">Submit</Button>
 </Form>

```

2022-11-17 03:45 UTC, pconrad requested changes
There are a few change that will make this PR a bit more complete.

2022-11-17 03:45 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
Let's also add this---it's a copy/paste/edit of the code for the test job:

```jsx
 // test job 

    const objectToAxiosParamsMilkCowsJob = (data) => ({
        url: `/api/jobs/launch/milkcows`,
        method: "POST"
    });

    // Stryker disable all
    const milkCowsJobMutation = useBackendMutation(
        objectToAxiosParamsMilkCowsJob,
        {  },
        ["/api/jobs/all"]
    );
    // Stryker enable all

    const submitMilkCowsJob = async (data) => {
        console.log("submitMilkCowsJob, data=", data);
        milkCowsJobMutation.mutate(data);
    }

```

Then, change this line: 

```jsx
form: <JobMilktheCows />
```

To this one: 

```jsx
form: <JobMilktheCows submitAction={submitMilkCowsJob}
```

That way, the entire frontend is ready to go... as soon as the backend is complete, the job will work.

2022-11-20 21:12 UTC, pconrad requested changes

2022-11-20 21:12 UTC, pconrad commented on frontend/src/main/components/Jobs/MilkCowsJobForm.js
> +};
We don't need these values for milking the cows; these are only needed for the test job.   We can remove these.

2022-11-20 21:12 UTC, pconrad commented on frontend/src/main/components/Jobs/MilkCowsJobForm.js
> +    { defaultValues: defaultValues }
For now, this can just be: 
```js
 {defaultValues: {} }
```

2022-11-25 22:52 UTC, pconrad approved these changes
LGTM

2022-11-28 03:43 UTC, BenYangSB reviewed
looks good

2022-11-28 06:32 UTC, merged